const NEWS_CATEGORY_BUSINESS = 'business';
const NEWS_CATEGORY_ENTERTAINMENT = 'entertainment';
const NEWS_CATEGORY_GENERAL = 'general';
const NEWS_CATEGORY_HEALTH = 'health';
const NEWS_CATEGORY_SCIENCE = 'science';
const NEWS_CATEGORY_SPORTS = 'sports';
const NEWS_CATEGORY_TECHNOLOGY = 'technology';

export {
  NEWS_CATEGORY_BUSINESS,
  NEWS_CATEGORY_ENTERTAINMENT,
  NEWS_CATEGORY_GENERAL,
  NEWS_CATEGORY_HEALTH,
  NEWS_CATEGORY_SCIENCE,
  NEWS_CATEGORY_SPORTS,
  NEWS_CATEGORY_TECHNOLOGY
};
